variables:
  DOCKER_HOST: tcp://192.168.178.29:2375

stages:
  - Build image
  - Push to local Registry

docker build:
  image: docker:stable
  stage: Build image
  script:
    - docker info
    - docker build -t tuttas/gvhanzeige .
  tags:
    - myrunner

docker pushlocal:
  image: docker:stable
  stage: Push to local Registry
  only:
    - master
  script:
    - echo "$LOCAL_REGISTRY" | docker login -u root --password-stdin service.joerg-tuttas.de:5555
    - docker build -t service.joerg-tuttas.de:5555/root/gvhanzeige .
    - docker push service.joerg-tuttas.de:5555/root/gvhanzeige
  tags:
    - myrunner
